export const localStorageKey = {
  LeftPanel: 'left-panel',
  threads: 'threads',
  messages: 'messages',
  theme: 'theme',
  modelProvider: 'model-provider',
  settingInterface: 'setting-appearance',
  settingGeneral: 'setting-general',
  settingCodeBlock: 'setting-code-block',
  settingLocalApiServer: 'setting-local-api-server',
  settingProxyConfig: 'setting-proxy-config',
  settingWebSearch: 'setting-web-search',
  settingWebPreview: 'setting-web-preview',
  settingAgentTools: 'setting-agent-tools',
  settingHardware: 'setting-hardware',
  settingVulkan: 'setting-vulkan',
  toolApproval: 'tool-approval',
  toolAvailability: 'tool-availability',
  mcpGlobalPermissions: 'mcp-global-permissions',
  lastUsedModel: 'last-used-model',
  lastUsedAssistant: 'last-used-assistant',
  defaultAssistantId: 'default-assistant-id',
  favoriteModels: 'favorite-models',
  modelOrder: 'model-order',
  modelFilter: 'model-filter',
  setupCompleted: 'setup-completed',
  threadManagement: 'thread-management',
  /** Conversation groups, one key per surface: `conversation-groups:home` etc. */
  conversationGroups: 'conversation-groups',
  recentSearches: 'recent-searches',
  agentMode: 'agent-mode',
  coworkDisplay: 'cowork-display',
  sessionMessaging: 'session-messaging',
  defaultEmbeddingModel: 'default-embedding-model',
  modelOverrides: 'model-overrides',
  contextBreakdown: 'context-breakdown',
  // Value predates the Cowork rename; changing it would orphan saved sessions.
  fileActivity: 'file-activity',
  coworkSessions: 'code-sessions',
  coworkActivity: 'cowork-activity',
  claudeCompat: 'claude-compat',
  coworkCheckpoints: 'cowork-checkpoints',
  keybindings: 'keybindings',
  referenceAliases: 'reference-aliases',
  projectInitDrafts: 'project-init-drafts',
  /** Measured model test results, preferred default model, dismissed hints. */
  modelEvidence: 'model-evidence',
  /** Model Doctor: observed tool-calling probe results, by model and settings. */
  modelDoctor: 'model-doctor',
  /** First-run guide progress: chosen intention, current step, skipped/done. */
  onboardingGuide: 'onboarding-guide',
  /** Split conversations: open or closed, the second pane's thread, width share. */
  splitConversation: 'split-conversation',
}

export const CACHE_EXPIRY_MS = 1000 * 60 * 60 * 24
