/**
 * Where two team tasks' declared changes meet, before either runs. AH-109.
 *
 * Declared scopes only: these tests prove the overlap check sees the shapes
 * an overlap can take (a file, a folder around it, a move, a delete, a lock
 * file both would regenerate), spelled any way Windows would accept, and that
 * it says nothing about reads or about tasks that are ordered.
 */
import { describe, expect, it } from 'vitest'
import {
  applyDecision,
  conflictKey,
  initialState,
  normalizeScopePath,
  readyTasks,
  refuseGraph,
  refuseUnresolved,
  runTeam,
  scopeConflicts,
  settle,
  type TaskResult,
  type TeamTask,
} from '@/lib/coworkTeam'

const task = (id: string, over: Partial<TeamTask> = {}): TeamTask => ({
  id,
  description: `do ${id}`,
  dependsOn: [],
  writes: [],
  ...over,
})

const ok = (t: TeamTask): TaskResult => ({
  taskId: t.id,
  ok: true,
  output: 'done',
  producedBy: t.id,
})

describe('a declared path', () => {
  it('is refused when it could name somewhere outside the project', () => {
    for (const bad of [
      '../x.ts',
      'a/../../x.ts',
      '/etc/passwd',
      'C:/Windows/x',
      'c:x',
      '\\\\server\\share\\x',
      '\\\\?\\C:\\x',
      '~/x',
      'notes.txt:stream',
      '',
    ]) {
      expect(normalizeScopePath(bad), bad).toBeNull()
    }
  })

  it('is read the way Windows reads it', () => {
    expect(normalizeScopePath('src\\lib\\a.ts')).toBe('src/lib/a.ts')
    expect(normalizeScopePath('./src/./a.ts')).toBe('src/a.ts')
    expect(normalizeScopePath('src/a.ts.')).toBe('src/a.ts')
    expect(normalizeScopePath('src/')).toBe('src')
    expect(normalizeScopePath('.')).toBe('')
  })

  it('outside the project refuses the whole team before anything runs', () => {
    expect(refuseGraph([task('a', { writes: ['../escape.ts'] })])).toContain(
      'a: ../escape.ts'
    )
    expect(
      refuseGraph([task('a', { renames: [{ from: 'x', to: 'C:/y' }] })])
    ).toContain('C:/y')
  })
})

describe('where two tasks meet', () => {
  const kinds = (tasks: TeamTask[]) =>
    scopeConflicts(tasks).flatMap((c) => c.overlaps.map((o) => o.kind))

  it('finds the same file however it is spelled', () => {
    const found = scopeConflicts([
      task('a', { writes: ['SRC\\Index.ts'] }),
      task('b', { writes: ['src/index.ts'] }),
    ])
    expect(found).toHaveLength(1)
    expect(found[0].tasks).toEqual(['a', 'b'])
    expect(found[0].overlaps[0]).toMatchObject({
      kind: 'same-file',
      paths: ['SRC/Index.ts', 'src/index.ts'],
    })
  })

  it('finds a folder and something inside it', () => {
    expect(
      kinds([task('a', { writes: ['src'] }), task('b', { writes: ['src/a.ts'] })])
    ).toEqual(['nested'])
    // A prefix of a name is not a parent folder.
    expect(
      kinds([task('a', { writes: ['src'] }), task('b', { writes: ['srcs/a.ts'] })])
    ).toEqual([])
  })

  it('finds either end of a move, and a delete', () => {
    expect(
      kinds([
        task('a', { renames: [{ from: 'old.ts', to: 'new.ts' }] }),
        task('b', { writes: ['old.ts'] }),
      ])
    ).toEqual(['rename'])
    expect(
      kinds([
        task('a', { renames: [{ from: 'old.ts', to: 'new.ts' }] }),
        task('b', { writes: ['new.ts'] }),
      ])
    ).toEqual(['rename'])
    expect(
      kinds([task('a', { deletes: ['lib'] }), task('b', { writes: ['lib/x.ts'] })])
    ).toEqual(['delete'])
  })

  it('finds the lock file two manifest changes would both regenerate', () => {
    const found = scopeConflicts([
      task('a', { writes: ['web/package.json'] }),
      task('b', { writes: ['web/yarn.lock'] }),
    ])
    expect(found[0].overlaps[0].kind).toBe('generated')
    expect(found[0].overlaps[0].note).toContain('regenerated by a change to web/package.json')
    // Two manifests in different folders regenerate different lock files.
    expect(
      kinds([
        task('a', { writes: ['a/Cargo.toml'] }),
        task('b', { writes: ['b/Cargo.toml'] }),
      ])
    ).toEqual([])
  })

  it('never treats reading as changing', () => {
    expect(
      scopeConflicts([
        task('a', { reads: ['src/index.ts'] }),
        task('b', { writes: ['src/index.ts'] }),
        task('c', { reads: ['src/index.ts'] }),
      ])
    ).toEqual([])
  })

  it('says nothing about tasks that are ordered', () => {
    expect(
      scopeConflicts([
        task('a', { writes: ['x.ts'] }),
        task('b', { writes: ['x.ts'], dependsOn: ['a'] }),
      ])
    ).toEqual([])
    expect(
      scopeConflicts([
        task('a', { writes: ['x.ts'] }),
        task('b', { writes: ['x.ts'], after: ['a'] }),
      ])
    ).toEqual([])
  })
})

describe('what the person decides', () => {
  const pair = [
    task('a', { writes: ['x.ts'], isolate: true }),
    task('b', { writes: ['x.ts'], isolate: true }),
  ]

  it('serializing removes the conflict without claiming a dependency', () => {
    const serialized = applyDecision(pair, {
      kind: 'serialize',
      first: 'a',
      then: 'b',
    })
    expect(scopeConflicts(serialized)).toEqual([])
    expect(serialized[1].after).toEqual(['a'])
    // Ordering after an isolated task is not waiting on its changes.
    expect(refuseGraph(serialized)).toBeNull()
  })

  it('an ordering-only edge starts the later task even when the first failed', () => {
    const tasks = applyDecision(pair, { kind: 'serialize', first: 'a', then: 'b' })
    const start = initialState(tasks)
    expect(readyTasks(tasks, start).map((t) => t.id)).toEqual(['a'])
    const afterFail = settle(tasks, start, 'a', 'failed')
    expect(afterFail.b.status).toBe('pending')
    expect(readyTasks(tasks, afterFail).map((t) => t.id)).toEqual(['b'])
  })

  it('a revised scope is looked at again', () => {
    const narrowed = applyDecision(pair, {
      kind: 'revise',
      task: 'b',
      writes: ['y.ts'],
    })
    expect(scopeConflicts(narrowed)).toEqual([])
    const stillOverlapping = applyDecision(pair, {
      kind: 'revise',
      task: 'b',
      writes: ['X.TS'],
    })
    expect(scopeConflicts(stillOverlapping)).toHaveLength(1)
  })

  it('an overlap nobody decided refuses the team, and an allowed one runs', async () => {
    const dispatched: string[] = []
    const run = (allowParallel?: Set<string>) =>
      runTeam(pair, {
        allowParallel,
        runTask: async (t) => {
          dispatched.push(t.id)
          return ok(t)
        },
      })

    const refused = await run()
    expect(refused.ok).toBe(false)
    expect(dispatched).toEqual([])

    const key = conflictKey(scopeConflicts(pair)[0])
    const allowed = await run(new Set([key]))
    expect(allowed.ok).toBe(true)
    expect(dispatched.sort()).toEqual(['a', 'b'])
  })

  it('an allowance is for the overlap that was shown, not a later one', () => {
    const key = conflictKey(scopeConflicts(pair)[0])
    const widened = applyDecision(pair, {
      kind: 'revise',
      task: 'b',
      writes: ['x.ts', 'z.ts'],
    })
    const both = applyDecision(widened, {
      kind: 'revise',
      task: 'a',
      writes: ['x.ts', 'z.ts'],
    })
    expect(refuseUnresolved(both, new Set([key]))).toContain('z.ts')
  })
})
