// The design's line icons, drawn by lucide-react (the desktop's icon set),
// under the short names the mobile design uses.
import type { CSSProperties } from 'react'
import {
  Activity,
  Cpu,
  Download,
  Eraser,
  Flame,
  FolderOpen,
  FolderTree,
  Gem,
  GitFork,
  Pickaxe,
  RotateCw,
  WrapText,
  ArrowLeft,
  ArrowUp,
  AtSign,
  BookOpen,
  Box,
  Brain,
  Briefcase,
  Bell,
  Bug,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Code,
  Columns2,
  Copy,
  CornerDownRight,
  Ellipsis,
  ExternalLink,
  Eye,
  File,
  FileCode,
  Flag,
  FlaskConical,
  Folder,
  FolderClosed,
  Gauge,
  GitBranch,
  GitMerge,
  GitPullRequest,
  Globe,
  GripVertical,
  Hammer,
  Hand,
  History,
  Image,
  Info,
  Key,
  Laptop,
  Lightbulb,
  ListTodo,
  ListTree,
  LoaderCircle,
  Lock,
  Map as MapIcon,
  MessagesSquare,
  Microscope,
  Mic,
  Video,
  Monitor,
  Paperclip,
  Pause,
  Pencil,
  PenLine,
  Pin,
  Play,
  Plus,
  QrCode,
  RefreshCw,
  ScanSearch,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  Shuffle,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Square,
  SquareSlash,
  SquareTerminal,
  Star,
  Terminal,
  Trash2,
  TriangleAlert,
  Upload,
  Users,
  Vote,
  WandSparkles,
  WifiOff,
  Workflow,
  Wrench,
  X,
  type LucideIcon,
} from 'lucide-react'

const ICONS = {
  activity: Activity,
  alert: TriangleAlert,
  at: AtSign,
  cpu2: Cpu,
  dl: Download,
  erase: Eraser,
  flame: Flame,
  fopen: FolderOpen,
  fork: GitFork,
  gem: Gem,
  pick: Pickaxe,
  rotate: RotateCw,
  tree: FolderTree,
  wrap: WrapText,
  back: ArrowLeft,
  bell: Bell,
  book: BookOpen,
  brain: Brain,
  branch: GitBranch,
  bug: Bug,
  bulb: Lightbulb,
  check: Check,
  chev: ChevronDown,
  chevl: ChevronLeft,
  chevr: ChevronRight,
  clip: Paperclip,
  clock: Clock,
  code: Code,
  copy: Copy,
  cowork: Briefcase,
  cube: Box,
  edit: Pencil,
  ext: ExternalLink,
  eye: Eye,
  file: File,
  filecode: FileCode,
  flag: Flag,
  flask: FlaskConical,
  flow: Workflow,
  folder: Folder,
  gauge: Gauge,
  globe: Globe,
  grip: GripVertical,
  group: FolderClosed,
  hammer: Hammer,
  hand: Hand,
  image: Image,
  info: Info,
  key: Key,
  laptop: Laptop,
  loader: LoaderCircle,
  lock: Lock,
  map: MapIcon,
  merge: GitMerge,
  micro: Microscope,
  mic: Mic,
  monitor: Monitor,
  more: Ellipsis,
  offline: WifiOff,
  opts: SlidersHorizontal,
  pause: Pause,
  pen: PenLine,
  phone: Smartphone,
  pin: Pin,
  play: Play,
  plus: Plus,
  pr: GitPullRequest,
  qr: QrCode,
  refresh: RefreshCw,
  rewind: History,
  rooms: MessagesSquare,
  scan: ScanSearch,
  search: Search,
  send2: Send,
  server: Server,
  settings: Settings,
  shield: Shield,
  shuffle: Shuffle,
  slash: SquareSlash,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  split: Columns2,
  sq: Square,
  star: Star,
  steer: CornerDownRight,
  term: SquareTerminal,
  terminal: Terminal,
  timeline: ListTree,
  todo: ListTodo,
  trash: Trash2,
  up: ArrowUp,
  upl: Upload,
  users: Users,
  vote: Vote,
  video: Video,
  wand: WandSparkles,
  wrench: Wrench,
  x: X,
} satisfies Record<string, LucideIcon>

export type IconId = keyof typeof ICONS

export function I({
  n,
  size,
  spin,
  className,
  style,
  strokeWidth = 1.75,
  label,
}: {
  n: IconId
  size?: number
  /** Turning, as for a run in progress. */
  spin?: boolean | 'slow'
  className?: string
  style?: CSSProperties
  strokeWidth?: number
  label?: string
}) {
  const Cmp = ICONS[n]
  return (
    <Cmp
      className={['i', className].filter(Boolean).join(' ')}
      style={{
        ...(size ? { width: size, height: size } : {}),
        ...(spin ? { animation: `spin ${spin === 'slow' ? 1.6 : 1}s linear infinite` } : {}),
        ...style,
      }}
      strokeWidth={strokeWidth}
      aria-hidden={label ? undefined : true}
      aria-label={label}
      role={label ? 'img' : undefined}
    />
  )
}
