/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemMonitorRouteImport } from './routes/system-monitor'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as CoworkRouteImport } from './routes/cowork'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms/index'
import { Route as ThreadsThreadIdRouteImport } from './routes/threads/$threadId'
import { Route as SettingsWebSearchRouteImport } from './routes/settings/web-search'
import { Route as SettingsShortcutsRouteImport } from './routes/settings/shortcuts'
import { Route as SettingsPermissionsRouteImport } from './routes/settings/permissions'
import { Route as SettingsMemoryRouteImport } from './routes/settings/memory'
import { Route as SettingsMcpServersRouteImport } from './routes/settings/mcp-servers'
import { Route as SettingsLocalApiServerRouteImport } from './routes/settings/local-api-server'
import { Route as SettingsInterfaceRouteImport } from './routes/settings/interface'
import { Route as SettingsHttpsProxyRouteImport } from './routes/settings/https-proxy'
import { Route as SettingsHardwareRouteImport } from './routes/settings/hardware'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsExtensionsRouteImport } from './routes/settings/extensions'
import { Route as SettingsClaudeCodeRouteImport } from './routes/settings/claude-code'
import { Route as SettingsAttachmentsRouteImport } from './routes/settings/attachments'
import { Route as SettingsAssistantRouteImport } from './routes/settings/assistant'
import { Route as SettingsAgentToolsRouteImport } from './routes/settings/agent-tools'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms/$roomId'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as LocalApiServerLogsRouteImport } from './routes/local-api-server/logs'
import { Route as SettingsProvidersIndexRouteImport } from './routes/settings/providers/index'
import { Route as SettingsProvidersProviderNameRouteImport } from './routes/settings/providers/$providerName'

const SystemMonitorRoute = SystemMonitorRouteImport.update({
  id: '/system-monitor',
  path: '/system-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const CoworkRoute = CoworkRouteImport.update({
  id: '/cowork',
  path: '/cowork',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsThreadIdRoute = ThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWebSearchRoute = SettingsWebSearchRouteImport.update({
  id: '/settings/web-search',
  path: '/settings/web-search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsShortcutsRoute = SettingsShortcutsRouteImport.update({
  id: '/settings/shortcuts',
  path: '/settings/shortcuts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPermissionsRoute = SettingsPermissionsRouteImport.update({
  id: '/settings/permissions',
  path: '/settings/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMemoryRoute = SettingsMemoryRouteImport.update({
  id: '/settings/memory',
  path: '/settings/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMcpServersRoute = SettingsMcpServersRouteImport.update({
  id: '/settings/mcp-servers',
  path: '/settings/mcp-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLocalApiServerRoute = SettingsLocalApiServerRouteImport.update({
  id: '/settings/local-api-server',
  path: '/settings/local-api-server',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsInterfaceRoute = SettingsInterfaceRouteImport.update({
  id: '/settings/interface',
  path: '/settings/interface',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHttpsProxyRoute = SettingsHttpsProxyRouteImport.update({
  id: '/settings/https-proxy',
  path: '/settings/https-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHardwareRoute = SettingsHardwareRouteImport.update({
  id: '/settings/hardware',
  path: '/settings/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsExtensionsRoute = SettingsExtensionsRouteImport.update({
  id: '/settings/extensions',
  path: '/settings/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsClaudeCodeRoute = SettingsClaudeCodeRouteImport.update({
  id: '/settings/claude-code',
  path: '/settings/claude-code',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAttachmentsRoute = SettingsAttachmentsRouteImport.update({
  id: '/settings/attachments',
  path: '/settings/attachments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAssistantRoute = SettingsAssistantRouteImport.update({
  id: '/settings/assistant',
  path: '/settings/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAgentToolsRoute = SettingsAgentToolsRouteImport.update({
  id: '/settings/agent-tools',
  path: '/settings/agent-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalApiServerLogsRoute = LocalApiServerLogsRouteImport.update({
  id: '/local-api-server/logs',
  path: '/local-api-server/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersIndexRoute = SettingsProvidersIndexRouteImport.update({
  id: '/settings/providers/',
  path: '/settings/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersProviderNameRoute =
  SettingsProvidersProviderNameRouteImport.update({
    id: '/settings/providers/$providerName',
    path: '/settings/providers/$providerName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/cowork': typeof CoworkRoute
  '/logs': typeof LogsRoute
  '/system-monitor': typeof SystemMonitorRoute
  '/local-api-server/logs': typeof LocalApiServerLogsRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/settings/agent-tools': typeof SettingsAgentToolsRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/claude-code': typeof SettingsClaudeCodeRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/hardware': typeof SettingsHardwareRoute
  '/settings/https-proxy': typeof SettingsHttpsProxyRoute
  '/settings/interface': typeof SettingsInterfaceRoute
  '/settings/local-api-server': typeof SettingsLocalApiServerRoute
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/web-search': typeof SettingsWebSearchRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/rooms/': typeof RoomsIndexRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
  '/settings/providers/': typeof SettingsProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/cowork': typeof CoworkRoute
  '/logs': typeof LogsRoute
  '/system-monitor': typeof SystemMonitorRoute
  '/local-api-server/logs': typeof LocalApiServerLogsRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/settings/agent-tools': typeof SettingsAgentToolsRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/claude-code': typeof SettingsClaudeCodeRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/hardware': typeof SettingsHardwareRoute
  '/settings/https-proxy': typeof SettingsHttpsProxyRoute
  '/settings/interface': typeof SettingsInterfaceRoute
  '/settings/local-api-server': typeof SettingsLocalApiServerRoute
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/web-search': typeof SettingsWebSearchRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/rooms': typeof RoomsIndexRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
  '/settings/providers': typeof SettingsProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/cowork': typeof CoworkRoute
  '/logs': typeof LogsRoute
  '/system-monitor': typeof SystemMonitorRoute
  '/local-api-server/logs': typeof LocalApiServerLogsRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/settings/agent-tools': typeof SettingsAgentToolsRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/claude-code': typeof SettingsClaudeCodeRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/hardware': typeof SettingsHardwareRoute
  '/settings/https-proxy': typeof SettingsHttpsProxyRoute
  '/settings/interface': typeof SettingsInterfaceRoute
  '/settings/local-api-server': typeof SettingsLocalApiServerRoute
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/web-search': typeof SettingsWebSearchRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/rooms/': typeof RoomsIndexRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
  '/settings/providers/': typeof SettingsProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/cowork'
    | '/logs'
    | '/system-monitor'
    | '/local-api-server/logs'
    | '/project/$projectId'
    | '/rooms/$roomId'
    | '/settings/agent-tools'
    | '/settings/assistant'
    | '/settings/attachments'
    | '/settings/claude-code'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/hardware'
    | '/settings/https-proxy'
    | '/settings/interface'
    | '/settings/local-api-server'
    | '/settings/mcp-servers'
    | '/settings/memory'
    | '/settings/permissions'
    | '/settings/shortcuts'
    | '/settings/web-search'
    | '/threads/$threadId'
    | '/rooms/'
    | '/settings/providers/$providerName'
    | '/settings/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifacts'
    | '/cowork'
    | '/logs'
    | '/system-monitor'
    | '/local-api-server/logs'
    | '/project/$projectId'
    | '/rooms/$roomId'
    | '/settings/agent-tools'
    | '/settings/assistant'
    | '/settings/attachments'
    | '/settings/claude-code'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/hardware'
    | '/settings/https-proxy'
    | '/settings/interface'
    | '/settings/local-api-server'
    | '/settings/mcp-servers'
    | '/settings/memory'
    | '/settings/permissions'
    | '/settings/shortcuts'
    | '/settings/web-search'
    | '/threads/$threadId'
    | '/rooms'
    | '/settings/providers/$providerName'
    | '/settings/providers'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/cowork'
    | '/logs'
    | '/system-monitor'
    | '/local-api-server/logs'
    | '/project/$projectId'
    | '/rooms/$roomId'
    | '/settings/agent-tools'
    | '/settings/assistant'
    | '/settings/attachments'
    | '/settings/claude-code'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/hardware'
    | '/settings/https-proxy'
    | '/settings/interface'
    | '/settings/local-api-server'
    | '/settings/mcp-servers'
    | '/settings/memory'
    | '/settings/permissions'
    | '/settings/shortcuts'
    | '/settings/web-search'
    | '/threads/$threadId'
    | '/rooms/'
    | '/settings/providers/$providerName'
    | '/settings/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRoute
  CoworkRoute: typeof CoworkRoute
  LogsRoute: typeof LogsRoute
  SystemMonitorRoute: typeof SystemMonitorRoute
  LocalApiServerLogsRoute: typeof LocalApiServerLogsRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  SettingsAgentToolsRoute: typeof SettingsAgentToolsRoute
  SettingsAssistantRoute: typeof SettingsAssistantRoute
  SettingsAttachmentsRoute: typeof SettingsAttachmentsRoute
  SettingsClaudeCodeRoute: typeof SettingsClaudeCodeRoute
  SettingsExtensionsRoute: typeof SettingsExtensionsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsHardwareRoute: typeof SettingsHardwareRoute
  SettingsHttpsProxyRoute: typeof SettingsHttpsProxyRoute
  SettingsInterfaceRoute: typeof SettingsInterfaceRoute
  SettingsLocalApiServerRoute: typeof SettingsLocalApiServerRoute
  SettingsMcpServersRoute: typeof SettingsMcpServersRoute
  SettingsMemoryRoute: typeof SettingsMemoryRoute
  SettingsPermissionsRoute: typeof SettingsPermissionsRoute
  SettingsShortcutsRoute: typeof SettingsShortcutsRoute
  SettingsWebSearchRoute: typeof SettingsWebSearchRoute
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  SettingsProvidersProviderNameRoute: typeof SettingsProvidersProviderNameRoute
  SettingsProvidersIndexRoute: typeof SettingsProvidersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system-monitor': {
      id: '/system-monitor'
      path: '/system-monitor'
      fullPath: '/system-monitor'
      preLoaderRoute: typeof SystemMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cowork': {
      id: '/cowork'
      path: '/cowork'
      fullPath: '/cowork'
      preLoaderRoute: typeof CoworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$threadId': {
      id: '/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/web-search': {
      id: '/settings/web-search'
      path: '/settings/web-search'
      fullPath: '/settings/web-search'
      preLoaderRoute: typeof SettingsWebSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/shortcuts': {
      id: '/settings/shortcuts'
      path: '/settings/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof SettingsShortcutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/permissions': {
      id: '/settings/permissions'
      path: '/settings/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof SettingsPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/memory': {
      id: '/settings/memory'
      path: '/settings/memory'
      fullPath: '/settings/memory'
      preLoaderRoute: typeof SettingsMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/mcp-servers': {
      id: '/settings/mcp-servers'
      path: '/settings/mcp-servers'
      fullPath: '/settings/mcp-servers'
      preLoaderRoute: typeof SettingsMcpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/local-api-server': {
      id: '/settings/local-api-server'
      path: '/settings/local-api-server'
      fullPath: '/settings/local-api-server'
      preLoaderRoute: typeof SettingsLocalApiServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/interface': {
      id: '/settings/interface'
      path: '/settings/interface'
      fullPath: '/settings/interface'
      preLoaderRoute: typeof SettingsInterfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/https-proxy': {
      id: '/settings/https-proxy'
      path: '/settings/https-proxy'
      fullPath: '/settings/https-proxy'
      preLoaderRoute: typeof SettingsHttpsProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/hardware': {
      id: '/settings/hardware'
      path: '/settings/hardware'
      fullPath: '/settings/hardware'
      preLoaderRoute: typeof SettingsHardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/extensions': {
      id: '/settings/extensions'
      path: '/settings/extensions'
      fullPath: '/settings/extensions'
      preLoaderRoute: typeof SettingsExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/claude-code': {
      id: '/settings/claude-code'
      path: '/settings/claude-code'
      fullPath: '/settings/claude-code'
      preLoaderRoute: typeof SettingsClaudeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/attachments': {
      id: '/settings/attachments'
      path: '/settings/attachments'
      fullPath: '/settings/attachments'
      preLoaderRoute: typeof SettingsAttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/assistant': {
      id: '/settings/assistant'
      path: '/settings/assistant'
      fullPath: '/settings/assistant'
      preLoaderRoute: typeof SettingsAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/agent-tools': {
      id: '/settings/agent-tools'
      path: '/settings/agent-tools'
      fullPath: '/settings/agent-tools'
      preLoaderRoute: typeof SettingsAgentToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-api-server/logs': {
      id: '/local-api-server/logs'
      path: '/local-api-server/logs'
      fullPath: '/local-api-server/logs'
      preLoaderRoute: typeof LocalApiServerLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers/': {
      id: '/settings/providers/'
      path: '/settings/providers'
      fullPath: '/settings/providers/'
      preLoaderRoute: typeof SettingsProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers/$providerName': {
      id: '/settings/providers/$providerName'
      path: '/settings/providers/$providerName'
      fullPath: '/settings/providers/$providerName'
      preLoaderRoute: typeof SettingsProvidersProviderNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRoute,
  CoworkRoute: CoworkRoute,
  LogsRoute: LogsRoute,
  SystemMonitorRoute: SystemMonitorRoute,
  LocalApiServerLogsRoute: LocalApiServerLogsRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  SettingsAgentToolsRoute: SettingsAgentToolsRoute,
  SettingsAssistantRoute: SettingsAssistantRoute,
  SettingsAttachmentsRoute: SettingsAttachmentsRoute,
  SettingsClaudeCodeRoute: SettingsClaudeCodeRoute,
  SettingsExtensionsRoute: SettingsExtensionsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsHardwareRoute: SettingsHardwareRoute,
  SettingsHttpsProxyRoute: SettingsHttpsProxyRoute,
  SettingsInterfaceRoute: SettingsInterfaceRoute,
  SettingsLocalApiServerRoute: SettingsLocalApiServerRoute,
  SettingsMcpServersRoute: SettingsMcpServersRoute,
  SettingsMemoryRoute: SettingsMemoryRoute,
  SettingsPermissionsRoute: SettingsPermissionsRoute,
  SettingsShortcutsRoute: SettingsShortcutsRoute,
  SettingsWebSearchRoute: SettingsWebSearchRoute,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  SettingsProvidersProviderNameRoute: SettingsProvidersProviderNameRoute,
  SettingsProvidersIndexRoute: SettingsProvidersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
