#!/bin/bash
# Stop at the first failure: without this a failed step (such as the bun copy
# below) still ended in a repackaged AppImage and exit 0 (#157).
set -euo pipefail

ARCH="${ARCH:-"$(uname -m)"}"
case "$ARCH" in
  x86_64|amd64)        ARCH="x86_64"  ;;
  i386|i486|i586|i686) ARCH="i386"    ;;
  arm64|aarch64)       ARCH="aarch64" ;;
  arm*)                ARCH="armhf"   ;;
esac

APPIMAGETOOL="./.cache/build-tools/appimagetool"
RELEASE_CHANNEL=${RELEASE_CHANNEL:-"stable"}

# appimagetool is itself an AppImage, so it mounts itself through FUSE, which
# the hosted runners no longer provide. This runs outside shim-linuxdeploy.sh,
# so it needs its own copy of the fallback.
export APPIMAGE_EXTRACT_AND_RUN=1

mkdir -p ./.cache/build-tools
wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-${ARCH}.AppImage -O "${APPIMAGETOOL}" || { echo "Failed to download appimagetool."; exit 1; }
chmod +x "${APPIMAGETOOL}"

if [ "${RELEASE_CHANNEL}" != "stable" ]; then
    APP_DIR=./src-tauri/target/release/bundle/appimage/Flint-${RELEASE_CHANNEL}.AppDir
else
    APP_DIR=./src-tauri/target/release/bundle/appimage/Flint.AppDir
fi

# bundle additional resources in the AppDir without pulling in their dependencies
cp ./src-tauri/resources/bin/bun "$APP_DIR/usr/bin/bun" || { echo "Failed to copy the bun sidecar into $APP_DIR."; exit 1; }

# The host's Vulkan loader and NVIDIA driver have to be the ones that run; a copy
# from the build host crashed every model load (janhq/jan#9173). shim-linuxdeploy.sh
# excludes them, so finding one here means that exclusion stopped applying.
HOST_LIBS=$(find "$APP_DIR" \( -name 'libvulkan.so*' -o -name 'libcuda.so*' \) 2>/dev/null)
if [ -n "$HOST_LIBS" ]; then
    echo "$APP_DIR bundles libraries that must come from the user's system:"
    echo "$HOST_LIBS"
    exit 1
fi

# remove appimage generated by tauri build
APP_IMAGE=./src-tauri/target/release/bundle/appimage/$(ls ./src-tauri/target/release/bundle/appimage/ | grep AppImage | head -1)
echo $APP_IMAGE
rm -f $APP_IMAGE

# repackage appimage with additional resources
"${APPIMAGETOOL}" $APP_DIR $APP_IMAGE
