; Generated by src-tauri/installer/generate.py. Do not edit.
; 1x pixel sizes of the wizard bitmaps, and the macro that embeds them.

!define FLINT_BTN_W_primary_continue 88
!define FLINT_BTN_W_primary_install 88
!define FLINT_BTN_W_primary_launch 102
!define FLINT_BTN_W_primary_finish 88
!define FLINT_BTN_W_primary_close 88
!define FLINT_BTN_W_outline_cancel 88
!define FLINT_BTN_W_outline_back 88
!define FLINT_BTN_W_outline_browse 88
!define FLINT_BTN_W_outline_close 88
!define FLINT_FIELD_W 328
!define FLINT_FIELD_H 32

!macro _FlintExtractWizard theme scale
  File "/oname=$PLUGINSDIR\flint\${theme}\${scale}\btn-primary-continue.bmp" "${FLINT_UI}\${theme}\${scale}\btn-primary-continue.bmp"
  File "/oname=$PLUGINSDIR\flint\${theme}\${scale}\btn-primary-install.bmp" "${FLINT_UI}\${theme}\${scale}\btn-primary-install.bmp"
  File "/oname=$PLUGINSDIR\flint\${theme}\${scale}\btn-primary-launch.bmp" "${FLINT_UI}\${theme}\${scale}\btn-primary-launch.bmp"
  File "/oname=$PLUGINSDIR\flint\${theme}\${scale}\btn-primary-finish.bmp" "${FLINT_UI}\${theme}\${scale}\btn-primary-finish.bmp"
  File "/oname=$PLUGINSDIR\flint\${theme}\${scale}\btn-primary-close.bmp" "${FLINT_UI}\${theme}\${scale}\btn-primary-close.bmp"
  File "/oname=$PLUGINSDIR\flint\${theme}\${scale}\btn-outline-cancel.bmp" "${FLINT_UI}\${theme}\${scale}\btn-outline-cancel.bmp"
  File "/oname=$PLUGINSDIR\flint\${theme}\${scale}\btn-outline-back.bmp" "${FLINT_UI}\${theme}\${scale}\btn-outline-back.bmp"
  File "/oname=$PLUGINSDIR\flint\${theme}\${scale}\btn-outline-browse.bmp" "${FLINT_UI}\${theme}\${scale}\btn-outline-browse.bmp"
  File "/oname=$PLUGINSDIR\flint\${theme}\${scale}\btn-outline-close.bmp" "${FLINT_UI}\${theme}\${scale}\btn-outline-close.bmp"
  File "/oname=$PLUGINSDIR\flint\${theme}\${scale}\field.bmp" "${FLINT_UI}\${theme}\${scale}\field.bmp"
  File "/oname=$PLUGINSDIR\flint\${theme}\${scale}\radio-on.bmp" "${FLINT_UI}\${theme}\${scale}\radio-on.bmp"
  File "/oname=$PLUGINSDIR\flint\${theme}\${scale}\radio-off.bmp" "${FLINT_UI}\${theme}\${scale}\radio-off.bmp"
!macroend
