name: Tauri Builder - Nightly / Manual

on:
  schedule:
    - cron: '0 20 * * 1,2,3' # At 8 PM UTC on Monday, Tuesday, and Wednesday which is 3 AM UTC+7 Tuesday, Wednesday, and Thursday
  workflow_dispatch:
    inputs:
      public_provider:
        type: choice
        description: 'Public Provider'
        options:
          - none
          - aws-s3
        default: none
      disable_updater:
        type: boolean
        description: 'If true, builds both .deb and .appimage but disables auto-updater'
        default: false
  pull_request:
    branches:
      - release/**
      - main
    paths:
      - '.github/workflows/jan-tauri-build-nightly.yaml'
      - '.github/workflows/template-get-update-version.yml'
      - '.github/workflows/template-tauri-build-macos.yml'
      - '.github/workflows/template-tauri-build-windows-x64.yml'
      - '.github/workflows/template-tauri-build-linux-x64.yml'
      - '.github/workflows/template-noti-discord-and-update-url-readme.yml'
      - 'src-tauri/**'
      - 'core/**'
      - 'web-app/**'
      - 'extensions/**'
      - 'scripts/**'
      - 'pre-install/**'
      - 'Makefile'
      - 'package.json'


concurrency:
  group: nightly-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set-public-provider:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    outputs:
      public_provider: ${{ steps.set-public-provider.outputs.public_provider }}
      ref: ${{ steps.set-public-provider.outputs.ref }}
    steps:
      - name: Set public provider
        id: set-public-provider
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "::set-output name=public_provider::${{ github.event.inputs.public_provider }}"
            echo "::set-output name=ref::${{ github.ref }}"
          else
            if [ "${{ github.event_name }}" == "schedule" ]; then
              echo "::set-output name=public_provider::aws-s3"
              echo "::set-output name=ref::refs/heads/main"
            elif [ "${{ github.event_name }}" == "push" ]; then
              echo "::set-output name=public_provider::aws-s3"
              echo "::set-output name=ref::${{ github.ref }}"
            elif [ "${{ github.event_name }}" == "pull_request_review" ]; then
              echo "::set-output name=public_provider::none"
              echo "::set-output name=ref::${{ github.ref }}"
            else
              echo "::set-output name=public_provider::none"
              echo "::set-output name=ref::${{ github.ref }}"
            fi
          fi
  # Job create Update app version based on latest release tag with build number and save to output
  get-update-version:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    uses: ./.github/workflows/template-get-update-version.yml

  build-macos:
    uses: ./.github/workflows/template-tauri-build-macos.yml
    needs: [get-update-version, set-public-provider]
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    secrets: inherit
    with:
      ref: ${{ needs.set-public-provider.outputs.ref }}
      public_provider: ${{ needs.set-public-provider.outputs.public_provider }}
      new_version: ${{ needs.get-update-version.outputs.new_version }}
      channel: nightly
      cortex_api_port: '39261'

  build-windows-x64:
    uses: ./.github/workflows/template-tauri-build-windows-x64.yml
    secrets: inherit
    needs: [get-update-version, set-public-provider]
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    with:
      ref: ${{ needs.set-public-provider.outputs.ref }}
      public_provider: ${{ needs.set-public-provider.outputs.public_provider }}
      new_version: ${{ needs.get-update-version.outputs.new_version }}
      channel: nightly
      cortex_api_port: '39261'
  build-linux-x64:
    uses: ./.github/workflows/template-tauri-build-linux-x64.yml
    secrets: inherit
    needs: [get-update-version, set-public-provider]
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    with:
      ref: ${{ needs.set-public-provider.outputs.ref }}
      public_provider: ${{ needs.set-public-provider.outputs.public_provider }}
      new_version: ${{ needs.get-update-version.outputs.new_version }}
      channel: nightly
      cortex_api_port: '39261'
      disable_updater: ${{ github.event.inputs.disable_updater == 'true' }}

  comment-pr-build-url:
    needs:
      [
        build-macos,
        build-windows-x64,
        build-linux-x64,
        get-update-version,
        set-public-provider,
      ]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_review'
    steps:
      - name: Set up GitHub CLI
        run: |
          curl -sSL https://github.com/cli/cli/releases/download/v2.33.0/gh_2.33.0_linux_amd64.tar.gz | tar xz
          sudo cp gh_2.33.0_linux_amd64/bin/gh /usr/local/bin/

      - name: Comment build URL on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL=${{ github.event.pull_request.html_url }}
          RUN_ID=${{ github.run_id }}
          COMMENT="This is the build for this pull request. You can download it from the Artifacts section here: [Build URL](https://github.com/${{ github.repository }}/actions/runs/${RUN_ID})."
          gh pr comment $PR_URL --body "$COMMENT"
